@startuml

entity Categories {
* id VARCHAR(100) <<PK>>
--
*  position INT
}

entity CategoriesTranslation {
* category_id VARCHAR(100) <<FK>> <<PK>>
* language VARCHAR(100) <<PK>>
--
* name VARCHAR(100)
description TEXT
}

Categories ||--o{ CategoriesTranslation

@enduml